### ISSUE TITLE
Create Section in Readme.md for how to download models

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/open_clip#1]
Create Section in Readme.md for how to download models
- for setup / in setup section

Include Links:
- https://huggingface.co/laion
- https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K

**Comment by skittoo** [comment]
The models are downloaded and cached automatically while using open_clip . 

I have made a notebook in notebooks section for downloading the models manually if you want to.
