### ISSUE TITLE
Update Example in Readme.md

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/open_clip#3]
>Usage

https://github.com/kk-digital/open_clip

```
text_probs = (100.0 * image_features @ text_features.T).softmax(dim=-1)
```
^ put comment over this line, that this cross entropy/soft max
^ put comment on own line that @ is vector/matrix multiplication and T is transpose

Put comment and then another calculation for Cosine similarity (normalize the vectors and do dot product). Or do dot product and divide by produce of vector lengths.
- also print the cosine similarity

---

In /noteooks/ put an example python notebook with code above (init, load, run, etc)

**Comment by skittoo** [comment]
Done
