### ISSUE TITLE
Example in /notebook/ of comparing image-image similarity

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/open_clip#5]
https://github.com/openai/CLIP/issues/1
- encode images
- take cosine similarity between two example images

- Put in main notebook as example of Image-Image similarity
-- just to remind us, that we can do this (to get similar images)
- Also make sure there is example of Image-Caption matching

**Comment by skittoo** [comment]
Done! ,, You can find Image-Image similarity.ipynb in notebooks folder
