### ISSUE TITLE
Copy "More Examples" from Clip to OpenClip Readme

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/open_clip#7]
https://github.com/kk-digital/CLIP

Copy: More Examples Section from Clip to OpenClip Readme.md
- Zero-Shot Prediction
- Linear-probe evaluation

Also, put the example code in the notebook in notebook/examples

- The Zero-shot for CIFAR does not need to run
-- but if dataset download function is easy and it does not take much time to get working, then its ok to do

- The Linear-probe evaluation example should run

**Comment by skittoo** [comment]
Done
